services:
  - type: web
    name: musicflow-backend
    env: python
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: bash -c "python manage.py migrate && gunicorn backend.wsgi:application"
    preDeployCommand: python manage.py createadmin
    envVars:
      - key: SECRET_KEY
        value: use-decouple-or-env
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-backend-url.onrender.com
      - key: DB_ENGINE
        value: django.db.backends.postgresql
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: ${DB_PORT}
