# Generated by Django 5.1.7 on 2025-03-26 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('FALHA', 'Falha')], max_length=20)),
                ('saida', models.TextField(blank=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processoautomatizado')),
            ],
        ),
    ]
