# Generated by Django 5.1.7 on 2025-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_execucaoprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoprocesso',
            name='data_execucao_agendada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaoprocesso',
            name='resumo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
