# Generated by Django 5.1.7 on 2025-03-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_execucaoprocesso_data_execucao_agendada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaoprocesso',
            name='data_execucao_agendada',
        ),
        migrations.AddField(
            model_name='processoautomatizado',
            name='data_execucao_agendada',
            field=models.DateTimeField(blank=True, help_text='Data/hora para execução automática do processo', null=True),
        ),
    ]
