# Generated by Django 5.1.7 on 2025-04-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_execucaoprocesso_data_execucao_agendada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoautomatizado',
            name='email_alerta',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
