# Generated by Django 5.1.7 on 2025-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_processoautomatizado_email_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaoprocesso',
            name='resumo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
